apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  namespace: mediawiki-dev
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - image: mdshoaib707/mediawiki-tg:minimized
          name: mediawiki
          ports:
            - containerPort: 80
              name: mediawiki-port
