apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim-dev
  namespace: mysql-dev
  labels:
    tier: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

