apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.claimname }}
  namespace: {{ .Values.namespace }}
  labels:
    tier: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.storagesize }}
